import { StyleSheet, Platform, StatusBar } from 'react-native';
import { Colors } from '../../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  backgroundLogo: {
    position: 'absolute',
    top: 150,
    left: -100,
    right: 0,
    bottom: 0,
    width: 530,
    height: 530,
    opacity: 0.15,
  },
  header: {
    backgroundColor: '#F8B657',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 8,
    paddingTop: Platform.OS === 'ios' ? 48 : StatusBar.currentHeight ? StatusBar.currentHeight + 12 : 30,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  backButton: {
    padding: 2,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  headerButton: {
    padding: 2,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    flexGrow: 1,
  },
  card: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.text,
    marginBottom: 16,
  },
  titleWithBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  cardTitleStyled: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.text,
    letterSpacing: 0.3,
  },
  countBadge: {
    backgroundColor: Colors.success,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  countBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.white,
  },
  companyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  bookmarkButton: {
    padding: 4,
    marginLeft: 8,
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.black50,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  avatarText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Colors.white,
  },
  companyInfo: {
    flex: 1,
    alignItems: 'flex-start',
  },
  companyNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  companyName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.text,
    marginBottom: 4,
    textAlign: 'left',
    flex: 1,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
    justifyContent: 'flex-start',
  },
  verifiedText: {
    fontSize: 12,
    color: Colors.success,
  },
  sectorsContainer: {
    marginTop: 12,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.black50,
  },
  sectorsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sectorChip: {
    backgroundColor: Colors.orange[400],
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  sectorText: {
    fontSize: 13,
    color: Colors.primary,
    fontWeight: '500',
  },
  capabilityItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.black20,
  },
  modernCapabilityItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    marginVertical: 6,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(248, 182, 87, 0.3)',
  },
  capabilityHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  capabilityIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.orange[400],
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  capabilityContent: {
    flex: 1,
  },
  modernCapabilityName: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.text,
    marginBottom: 4,
    lineHeight: 22,
  },
  modernCapabilityDetail: {
    fontSize: 14,
    color: Colors.black50,
    lineHeight: 20,
    marginBottom: 2,
  },
  capabilityTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  modernCapabilityTypeBadge: {
    backgroundColor: 'rgba(248, 182, 87, 0.85)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  modernCapabilityTypeText: {
    fontSize: 12,
    color: Colors.white,
    fontWeight: '600',
  },
  localContentBadge: {
    backgroundColor: Colors.success,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  localContentBadgeText: {
    fontSize: 12,
    color: Colors.white,
    fontWeight: '600',
  },
  capabilityGroupContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    marginVertical: 6,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(248, 182, 87, 0.3)',
    overflow: 'hidden',
  },
  capabilityGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: 'rgba(248, 182, 87, 0.05)',
  },
  capabilityGroupLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  capabilityGroupTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.text,
    flex: 1,
  },
  groupCountBadge: {
    backgroundColor: Colors.primary,
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  groupCountText: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.white,
  },
  capabilityGroupItems: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  capabilitySubItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 12,
    paddingLeft: 12,
    paddingRight: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(248, 182, 87, 0.15)',
  },
  subItemIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
    minWidth: 36,
  },
  subItemBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.primary,
    marginRight: 6,
  },
  subItemNumber: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.primary,
    minWidth: 20,
  },
  capabilitySubContent: {
    flex: 1,
  },
  capabilitySubItemName: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.text,
    marginBottom: 8,
    lineHeight: 20,
  },
  summaryContainer: {
    marginTop: 12,
  },
  summaryText: {
    fontSize: 14,
    color: Colors.text,
    lineHeight: 20,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.black20,
    marginTop: 8,
  },
  actionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.orange[400],
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  actionText: {
    flex: 1,
    fontSize: 14,
    color: Colors.text,
    fontWeight: '500',
  },
  badgesContainer: {
    marginBottom: 12,
  },
  badgesList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  diversityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8F5E8',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 4,
  },
  badgeText: {
    fontSize: 12,
    color: Colors.success,
    fontWeight: '500',
  },
  badgeRow: {
    marginVertical: 8,
  },
  specialBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.orange[400],
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    gap: 6,
  },
  specialBadgeText: {
    fontSize: 13,
    color: Colors.primary,
    fontWeight: '600',
  },
  certificationsContainer: {
    marginTop: 12,
  },
  certificationsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  certificationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.orange[400],
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  certificationText: {
    fontSize: 12,
    color: Colors.text,
    fontWeight: '500',
  },
  quickActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginHorizontal: 16,
    marginTop: 20,
    gap: 12,
  },
  actionButton: {
    flex: 1,
    backgroundColor: Colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    gap: 4,
  },
  actionButtonText: {
    fontSize: 11,
    color: Colors.white,
    fontWeight: '500',
    textAlign: 'center',
  },
  clickableCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  clickableCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  clickableCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  clickableCardText: {
    marginLeft: 12,
    flex: 1,
  },
  clickableCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.text,
    marginBottom: 4,
  },
  clickableCardSubtitle: {
    fontSize: 14,
    color: Colors.black50,
    lineHeight: 20,
  },
  collapsibleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 8,
  },
  collapsibleContent: {
    marginTop: 8,
  },
  previewContainer: {
    marginTop: 12,
  },
  previewTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  previewTag: {
    backgroundColor: Colors.orange[400],
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  previewTagText: {
    fontSize: 12,
    color: Colors.primary,
    fontWeight: '500',
  },
  moreTag: {
    backgroundColor: '#F0F0F0',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  moreTagText: {
    fontSize: 12,
    color: Colors.black50,
    fontWeight: '500',
  },
  newsContainer: {
    padding: 16,
  },
  newsPlaceholder: {
    fontSize: 14,
    color: Colors.black50,
    lineHeight: 20,
    marginBottom: 16,
    textAlign: 'center',
  },
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: Colors.orange[400],
    borderRadius: 8,
  },
  viewAllText: {
    fontSize: 14,
    color: Colors.primary,
    fontWeight: '600',
  },
  projectsContainer: {
    maxHeight: 400,
  },
  projectItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.black20,
  },
  projectHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  projectName: {
    fontSize: 15,
    fontWeight: '600',
    color: Colors.text,
    flex: 1,
  },
  projectDate: {
    fontSize: 12,
    color: Colors.black50,
  },
  projectClient: {
    fontSize: 13,
    color: Colors.black50,
    marginBottom: 4,
    fontStyle: 'italic',
  },
  projectDescription: {
    fontSize: 13,
    color: Colors.text,
    lineHeight: 18,
    marginVertical: 4,
  },
  projectValue: {
    fontSize: 13,
    color: Colors.success,
    fontWeight: '500',
    marginTop: 4,
  },
  projectOutcome: {
    marginTop: 8,
    padding: 8,
    backgroundColor: Colors.orange[400],
    borderRadius: 6,
  },
  projectOutcomeLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.black50,
    marginBottom: 2,
  },
  projectOutcomeText: {
    fontSize: 12,
    color: Colors.text,
    lineHeight: 16,
  },
  noDataText: {
    fontSize: 14,
    color: Colors.black50,
    textAlign: 'center',
    paddingVertical: 20,
    fontStyle: 'italic',
  },
  paginationContainer: {
    alignItems: 'center',
    marginTop: 24,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(248, 182, 87, 0.2)',
    gap: 16,
  },
  pageDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pageDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(248, 182, 87, 0.3)',
  },
  pageDotActive: {
    backgroundColor: Colors.primary,
    width: 24,
    borderRadius: 4,
  },
  navigationButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(248, 182, 87, 0.1)',
    borderRadius: 20,
    padding: 4,
    gap: 12,
  },
  navButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navButtonDisabled: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
  },
  pageInfo: {
    flexDirection: 'row',
    alignItems: 'baseline',
    minWidth: 40,
    justifyContent: 'center',
  },
  pageNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.primary,
  },
  totalPages: {
    fontSize: 14,
    color: Colors.black50,
    fontWeight: '500',
  },
  itemsCount: {
    fontSize: 12,
    color: Colors.black50,
    textAlign: 'center',
  },
  bottomPagination: {
    borderTopColor: 'rgba(248, 182, 87, 0.2)',
    borderBottomWidth: 0,
    paddingBottom: 0,
    marginBottom: 0,
  },
  simplePaginationContainer: {
    alignItems: 'center',
    marginVertical: 12,
  },
  compactPagination: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(248, 182, 87, 0.08)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 12,
  },
  compactNavButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(248, 182, 87, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  compactNavButtonDisabled: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
  },
  compactPageDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  compactPageDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(248, 182, 87, 0.4)',
  },
  compactPageDotActive: {
    backgroundColor: Colors.primary,
    width: 18,
    borderRadius: 3,
  },
  separatedPaginationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 12,
    paddingHorizontal: 20,
  },
  separatedNavButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(248, 182, 87, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(248, 182, 87, 0.3)',
  },
  separatedNavButtonDisabled: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  centerPageDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(248, 182, 87, 0.08)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
  },
  adaptivePaginationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 16,
    paddingHorizontal: 20,
  },
  adaptivePageInfo: {
    alignItems: 'center',
    gap: 8,
  },
  adaptivePageText: {
    fontSize: 11,
    color: Colors.black50,
    fontWeight: '500',
  },
  horizontalPaginationWrapper: {
    marginVertical: 16,
  },
  horizontalPaginationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    gap: 12,
  },
  extendedPageDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(248, 182, 87, 0.08)',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    flex: 1,
    justifyContent: 'center',
  },
  inlinePaginationItemCount: {
    fontSize: 11,
    color: Colors.black50,
    fontWeight: '500',
    minWidth: 80,
    textAlign: 'right',
  },
  itemsCountBadge: {
    backgroundColor: Colors.success,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    minWidth: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemsCountBadgeText: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  metricsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  metricCard: {
    flex: 1,
    backgroundColor: 'rgba(248, 182, 87, 0.05)',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(248, 182, 87, 0.15)',
  },
  metricIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  metricLabel: {
    fontSize: 12,
    color: Colors.black50,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 4,
  },
  metricValue: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.text,
    textAlign: 'center',
  },
  metricPlaceholder: {
    fontSize: 12,
    color: Colors.black50,
    fontStyle: 'italic',
  },
  additionalMetricsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  additionalMetricCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(34, 197, 94, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 6,
  },
  additionalMetricIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  additionalMetricText: {
    fontSize: 12,
    color: Colors.success,
    fontWeight: '600',
  },
  modernQuickActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginTop: 24,
    marginBottom: 20,
    gap: 12,
  },
  modernActionButton: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(248, 182, 87, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  modernActionIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(248, 182, 87, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  modernActionButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.text,
    textAlign: 'center',
    marginBottom: 2,
  },
  modernActionButtonSubtext: {
    fontSize: 11,
    color: Colors.black50,
    textAlign: 'center',
    lineHeight: 14,
  },
  abnContainer: {
    backgroundColor: 'rgba(248, 182, 87, 0.08)',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(248, 182, 87, 0.2)',
  },
  abnText: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.text,
    letterSpacing: 1,
    marginBottom: 4,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  addressText: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.text,
    lineHeight: 20,
  },
  summaryToggleButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
    marginTop: 6,
  },
  diversityContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  diversityChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(76, 175, 80, 0.3)',
    gap: 6,
  },
  diversityText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.success,
  },
  certificationChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(248, 182, 87, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(248, 182, 87, 0.3)',
    gap: 6,
  },
  modernProjectItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    marginVertical: 6,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(248, 182, 87, 0.3)',
  },
  projectMainInfo: {
    marginBottom: 12,
  },
  projectTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  projectClientBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(248, 182, 87, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(248, 182, 87, 0.3)',
    gap: 4,
  },
  projectClientText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.primary,
  },
  projectDateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    gap: 4,
  },
  projectDateText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.black50,
  },
  projectValueBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(76, 175, 80, 0.3)',
    gap: 4,
  },
  projectValueText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.success,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.black20,
  },
  contactIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.orange[400],
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  contactIconDisabled: {
    backgroundColor: '#F0F0F0',
  },
  contactContent: {
    flex: 1,
  },
  contactLabel: {
    fontSize: 12,
    color: Colors.black50,
    marginBottom: 2,
  },
  contactValue: {
    fontSize: 14,
    color: Colors.text,
  },
  placeholderText: {
    fontStyle: 'italic',
    color: Colors.black50,
  },
});